# Netflix Data Cleaning Project 🍿
## Objective
Clean and preprocess the Netflix Movies and TV Shows dataset using Pandas.

We will handle missing values, fix data types, clean messy columns, and export a clean dataset.

In [16]:
import os
print(os.getcwd())

C:\Users\Rahul\Netflix Data Cleaning\notebook

In [18]:
print(os.listdir())

['.ipynb_checkpoints', 'Netflix_Data_Cleaning.ipynb']

In [2]:
# Import Libraries
import pandas as pd
import numpy as np

## 1. Load Dataset

In [22]:
df = pd.read_csv('../data/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

## 2. Dataset Overview

In [25]:
df.shape

(8807, 12)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [29]:
df.describe(include='all')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8807.000000,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,NaN,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,NaN,3207,1793,362,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.180198,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.819312,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

## 3. Check Missing Values

In [32]:
df.isnull().sum().sort_values(ascending=False)

director        2634
country          831
cast             825
date_added        10
rating             4
duration           3
show_id            0
type               0
title              0
release_year       0
listed_in          0
description        0
dtype: int64

## 4. Handle Missing Values

In [35]:
# Fill categorical missing values
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Not Available')
df['country'] = df['country'].fillna(df['country'].mode()[0])
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

## 5. Convert Date Column

In [38]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df['date_added'].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[ns]

## 6. Clean Duration Column

In [55]:
# Extract numeric duration
df['duration_number'] = df['duration'].str.extract(r'(\d+)').astype(float)

# Extract unit (min or Seasons)
df['duration_unit'] = df['duration'].str.extract('([A-Za-z]+)')

df[['duration', 'duration_number', 'duration_unit']].head()

    duration  duration_number duration_unit
0     90 min             90.0           min
1  2 Seasons              2.0       Seasons
2   1 Season              1.0        Season
3   1 Season              1.0        Season
4  2 Seasons              2.0       Seasons

## 7. Remove Duplicates

In [44]:
df.drop_duplicates(inplace=True)

## 8. Clean Column Names

In [47]:
df.columns = df.columns.str.lower()
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'duration_number', 'duration_unit'],
      dtype='object')

## 9. Final Check

In [61]:


df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])

df['duration'] = df['duration'].fillna("Unknown")
df['duration_number'] = df['duration_number'].fillna(0)
df['duration_unit'] = df['duration_unit'].fillna("Unknown")

In [63]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   show_id          8807 non-null   object
 1   type             8807 non-null   object
 2   title            8807 non-null   object
 3   director         8807 non-null   object
 4   cast             8807 non-null   object
 5   country          8807 non-null   object
 6   date_added       8807 non-null   datetime64[ns]
 7   release_year     8807 non-null   int64
 8   rating           8807 non-null   object
 9   duration         8807 non-null   object
 10  listed_in        8807 non-null   object
 11  description      8807 non-null   object
 12  duration_number  8807 non-null   float64
 13  duration_unit    8807 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(11)
memory usage: 963.4+ KB

show_id            0
type               0
title              0
director           0
cast               0
country            0
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
description        0
duration_number    0
duration_unit      0
dtype: int64

# 10. FINAL VALIDATION CHECK

In [66]:

print("Missing values:\n", df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

Missing values:
 show_id            0
type               0
title              0
director           0
cast               0
country            0
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
description        0
duration_number    0
duration_unit      0
dtype: int64
Duplicates: 0

# 11. Save cleaned dataset

In [69]:
df.to_csv('../data/netflix_titles_cleaned.csv', index=False)
print('Cleaned dataset saved successfully!')

Cleaned dataset saved successfully!

# Conclusion
We successfully cleaned the Netflix dataset by:
- Handling missing values
- Fixing data types
- Cleaning duration column
- Removing duplicates
- Exporting cleaned dataset